# frozen_string_literal: true


source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.9"

gem "tty-spinner", "~> 0.9.3"

gem "pastel", "~> 0.8.0"

gem "tty-box", "~> 0.6.0"

gem "ruby2d", "~> 0.9.4"

gem "colorize", "~> 0.8.1"
